apiVersion: v1
kind: Pod
metadata:
  name: lion-app
  labels:
    app: lion-app
spec:
  imagePullSecrets:
      - name: regcred
  containers:
      - name: lion-app
        image: docker pull likelion-cr-jh.kr.ncr.ntruss.com/lion-app:sqlite
        imagePullPolicy: Always #이미지 이름 같아도 받아옴
        envFrom:
          - secretRef:
              name: django-secret
          - secretRef:
              name: db-secret
          - configMapRef:
              name: django-config

        ports:
            - containerPort: 8000
