apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lion-app
  labels:
    app: lion-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lion-app
  template:
    metadata:
      labels:
        app: lion-app
    spec:
      containers:
        - name: lion
          image: teacherssamko/simple-web:v1
          ports:
            - containerPort: 8000

