apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello world"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ quote .Values.favorite.food | upper }}
  {{ if eq .Values.favorites.drink "coffee" }}mug: true{{ end }}